[Bugfix] Move error checking closer to file read
Previously, if (height > 0 && width > 0) was true, the
cv::resize() function would be called before cv_img_origin was
confirmed valid; if the image file/filename was not valid, this
caused an opencv assert error like this:

terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/A3p0_4200_32550/batserve/A3p0/glnxa64/OpenCV/modules/imgproc/src/imgwarp.cpp:1725: error: (-215)
  ssize.area() > 0 in function resize


Former-commit-id: babdef9ec1f3e339d09c87e0860804524bb254e8 [formerly aecab61ff762eb4fb595b59948b25a5d10cd5505]
Former-commit-id: 6ce90f82bae759f0989a93c130f1b09f3cfe94a2